name: GH pages

on: 
  push:
    branches: 
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Build
        run: npm run predeploy
      - name: Deploy
        run: npm run deploy


